

- name: stop vm's
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yaml
  tasks:
    - name: guest shutdown
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ item }}"
        state: shutdown-guest
        state_change_timeout: 120
      ignore_errors: true

      loop:
       - "{{ vm_name_jumpbox}}"
      # - "{{ vm_name_router}}"
       - "{{ vm_name_vcenter7}}"
    